### ISSUE TITLE
请问如何调整默认不是打开状态的参数

### ISSUE THREAD

**Issue by xJoyLu** [Uyukisan/MyukiGCard#3]
这个插件使用得很舒服，我想应用在我所有项目跳转串联；
我想设置为默认关闭状态，然后自定义位置

**Comment by Uyukisan** [comment]
> 这个插件使用得很舒服，我想应用在我所有项目跳转串联；
> 我想设置为默认关闭状态，然后自定义位置

设置defaultClosed为true，自定义位置不支持，对于移动端来说，中间位置无疑是最好的

**Comment by xJoyLu** [comment]
感谢更新😍
顺带提个文本错误：  
name: 可是是名字、网站名称等
应该是「可以是」吧
自定义位置可能太个性化需求了
你说的很对，我选择改CSS 😁

**Comment by Uyukisan** [comment]
哈哈，手敲键盘是这样的；对，你可以改CSS，margin之类的
